/*
  # Insert GLP Agonists Products

  New Tables/Changes:
  - Inserts Retatrutide (10mg, 20mg, 30mg, 50mg, 100mg)
  - Inserts Tirzepatide (10mg, 20mg, 30mg)
  - Inserts Semaglutide (10mg)
  All with category "GLP Agonists", badge_text "99% PURE", stock_status "in_stock"
*/

INSERT INTO products (name, slug, category, price, price_max, description, short_description, highlights, dosage, dosage_options, image_url, badge_text, is_featured, is_new_arrival, stock_status, related_product_slugs, wc_product_id)
VALUES
(
  'Retatrutide (10mg)',
  'retatrutide-10mg',
  'GLP Agonists',
  180.00,
  NULL,
  'Retatrutide is a tri-receptor agonist targeting GLP-1, GIP, and glucagon receptors. Research indicates significant potential for metabolic regulation and weight reduction.',
  'Tri-receptor GLP-1/GIP/glucagon agonist for metabolic research.',
  ARRAY['Tri-receptor GLP-1/GIP/glucagon agonist', 'Studied for significant weight reduction', 'Research explores metabolic rate improvement', 'Appetite suppression research'],
  '10mg',
  ARRAY['10mg'],
  '/images/products/v2_glp3r.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Retatrutide (20mg)',
  'retatrutide-20mg',
  'GLP Agonists',
  275.00,
  NULL,
  'Retatrutide is a tri-receptor agonist targeting GLP-1, GIP, and glucagon receptors. Research indicates significant potential for metabolic regulation and weight reduction.',
  'Tri-receptor GLP-1/GIP/glucagon agonist for metabolic research.',
  ARRAY['Tri-receptor GLP-1/GIP/glucagon agonist', 'Studied for significant weight reduction', 'Research explores metabolic rate improvement', 'Appetite suppression research'],
  '20mg',
  ARRAY['20mg'],
  '/images/products/v2_glp3r.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Retatrutide (30mg)',
  'retatrutide-30mg',
  'GLP Agonists',
  375.00,
  NULL,
  'Retatrutide is a tri-receptor agonist targeting GLP-1, GIP, and glucagon receptors. Research indicates significant potential for metabolic regulation and weight reduction.',
  'Tri-receptor GLP-1/GIP/glucagon agonist for metabolic research.',
  ARRAY['Tri-receptor GLP-1/GIP/glucagon agonist', 'Studied for significant weight reduction', 'Research explores metabolic rate improvement', 'Appetite suppression research'],
  '30mg',
  ARRAY['30mg'],
  '/images/products/v2_glp3r.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Retatrutide (50mg)',
  'retatrutide-50mg',
  'GLP Agonists',
  475.00,
  NULL,
  'Retatrutide is a tri-receptor agonist targeting GLP-1, GIP, and glucagon receptors. Research indicates significant potential for metabolic regulation and weight reduction.',
  'Tri-receptor GLP-1/GIP/glucagon agonist for metabolic research.',
  ARRAY['Tri-receptor GLP-1/GIP/glucagon agonist', 'Studied for significant weight reduction', 'Research explores metabolic rate improvement', 'Appetite suppression research'],
  '50mg',
  ARRAY['50mg'],
  '/images/products/v2_glp3r.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Retatrutide (100mg)',
  'retatrutide-100mg',
  'GLP Agonists',
  650.00,
  NULL,
  'Retatrutide is a tri-receptor agonist targeting GLP-1, GIP, and glucagon receptors. Research indicates significant potential for metabolic regulation and weight reduction.',
  'Tri-receptor GLP-1/GIP/glucagon agonist for metabolic research.',
  ARRAY['Tri-receptor GLP-1/GIP/glucagon agonist', 'Studied for significant weight reduction', 'Research explores metabolic rate improvement', 'Appetite suppression research'],
  '100mg',
  ARRAY['100mg'],
  '/images/products/v2_glp3r.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Tirzepatide (10mg)',
  'tirzepatide-10mg',
  'GLP Agonists',
  180.00,
  NULL,
  'Tirzepatide is a dual GLP-1/GIP receptor agonist being researched for its effects on weight loss, glucose control, and metabolic health.',
  'Dual GLP-1/GIP receptor agonist for metabolic and weight research.',
  ARRAY['Dual GLP-1/GIP receptor agonist', 'Studied for weight loss and glucose control', 'Research explores insulin sensitivity', 'Appetite and satiety regulation research'],
  '10mg',
  ARRAY['10mg'],
  '/images/products/v2_tirzepatide.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Tirzepatide (20mg)',
  'tirzepatide-20mg',
  'GLP Agonists',
  275.00,
  NULL,
  'Tirzepatide is a dual GLP-1/GIP receptor agonist being researched for its effects on weight loss, glucose control, and metabolic health.',
  'Dual GLP-1/GIP receptor agonist for metabolic and weight research.',
  ARRAY['Dual GLP-1/GIP receptor agonist', 'Studied for weight loss and glucose control', 'Research explores insulin sensitivity', 'Appetite and satiety regulation research'],
  '20mg',
  ARRAY['20mg'],
  '/images/products/v2_tirzepatide.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Tirzepatide (30mg)',
  'tirzepatide-30mg',
  'GLP Agonists',
  375.00,
  NULL,
  'Tirzepatide is a dual GLP-1/GIP receptor agonist being researched for its effects on weight loss, glucose control, and metabolic health.',
  'Dual GLP-1/GIP receptor agonist for metabolic and weight research.',
  ARRAY['Dual GLP-1/GIP receptor agonist', 'Studied for weight loss and glucose control', 'Research explores insulin sensitivity', 'Appetite and satiety regulation research'],
  '30mg',
  ARRAY['30mg'],
  '/images/products/v2_tirzepatide.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
),
(
  'Semaglutide (10mg)',
  'semaglutide-10mg',
  'GLP Agonists',
  180.00,
  NULL,
  'Semaglutide is a GLP-1 receptor agonist being studied for weight management, cardiovascular benefits, and blood glucose regulation.',
  'GLP-1 receptor agonist for weight management and metabolic research.',
  ARRAY['GLP-1 receptor agonist', 'Studied for weight management', 'Research explores cardiovascular benefits', 'Blood glucose regulation research'],
  '10mg',
  ARRAY['10mg'],
  '/images/products/v2_glp2t.webp',
  '99% PURE',
  false,
  false,
  'in_stock',
  ARRAY[]::text[],
  NULL
);
